version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - env
      - echo "Logging into Amazon Web Services Elastic Container Repository..."
      - aws ecr get-login --region $(PROJECT_REGION) --no-include-email
  build:
    commands:
      - echo "Building Docker image..."
      - docker build --squash -q -t $(PROJECT_NAME):$(CODEBUILD_RESOLVED_SOURCE_VERSION) .
      - echo "Pushing image to repository... "
      - docker tag $(PROJECT_NAME):$(CODEBUILD_RESOLVED_SOURCE_VERSION) $(PROJECT_REPOSITORY):$(CODEBUILD_RESOLVED_SOURCE_VERSION)
      - docker push $(PROJECT_REPOSITORY)
