version: '3.7'
services:
  elasticdns:
    container_name: elasticdns
    build: .
    image: elasticdns:latest
    init: true
    read_only: true
    environment:
      - ELASTICDNS_HOSTZONE_ID=AAAAAAAAAAAAAAAAAAA
      - ELASTICDNS_RECORD_SET=www.example.com
      - ELASTICDNS_TTL=300
      - ELASTICDNS_RECORD_TYPE=A
      - ELASTICDNS_COMMENT=
      - ELASTICDNS_PROFILE=
      - ELASTICDNS_SLEEP_SECONDS=300
      - ELASTICDNS_IP_LOG=/var/log/elasticdns/elasticdns.ip
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
    restart: unless-stopped